import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import { assetPath } from "@/lib/asset";
import { getService, projectRoute, servicePages } from "@/lib/services";
import { absoluteUrl, SITE_NAME } from "@/lib/site";

type PageProps = { params: Promise<{ slug: string }> };
export function generateStaticParams() { return servicePages.map((service) => ({ slug: service.slug })); }
export async function generateMetadata({ params }: PageProps): Promise<Metadata> { const { slug } = await params; const service = getService(slug); if (!service) return { title: `Service not found | ${SITE_NAME}` }; return { title: `${service.title} | ${SITE_NAME}`, description: service.intro, alternates: { canonical: absoluteUrl(`/services/${service.slug}/`) }, openGraph: { title: `${service.title} | ${SITE_NAME}`, description: service.intro, url: absoluteUrl(`/services/${service.slug}/`), type: "website" } }; }

export default async function ServicePage({ params }: PageProps) {
  const { slug } = await params; const service = getService(slug); if (!service) notFound();
  const jsonLd = { "@context": "https://schema.org", "@type": "Service", name: service.title, description: service.intro, provider: { "@type": "Organization", name: SITE_NAME, url: absoluteUrl("/") }, areaServed: "Morocco" };
  return <><Nav /><main className="case-study-page bg-paper text-ink"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><header className="mx-auto max-w-7xl px-6 pb-16 pt-32 md:px-10 md:pb-24 md:pt-44"><p className="case-study-kicker">SERVICE / {service.index}</p><h1 className="case-study-title mt-5 max-w-5xl">{service.title}</h1><p className="case-study-copy mt-8 max-w-2xl">{service.intro}</p></header><div className="mx-auto max-w-7xl px-6 md:px-10"><section className="grid gap-8 border-t border-ink/15 py-16 md:grid-cols-12 md:gap-12 md:py-24"><div className="md:col-span-4"><p className="case-study-index">01 — What we do</p></div><div className="md:col-span-8"><ul className="grid gap-4 sm:grid-cols-2">{service.capabilities.map((capability) => <li key={capability} className="border-b border-ink/15 pb-4 font-display text-2xl font-bold uppercase">{capability}</li>)}</ul></div></section><section className="grid gap-8 border-t border-ink/15 py-16 md:grid-cols-12 md:gap-12 md:py-24"><div className="md:col-span-4"><p className="case-study-index">02 — Our approach</p></div><p className="case-study-copy md:col-span-8">{service.approach}</p></section><section className="border-t border-ink/15 py-16 md:py-24"><p className="case-study-index">03 — Selected work</p><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{service.relatedProjects.map((project) => <Link key={project.slug} href={projectRoute(project)} className="group"><div className="relative aspect-[4/5] overflow-hidden bg-ink"><Image src={assetPath(project.image ?? "")} alt={`${project.title} ${service.title.toLowerCase()} project by KORIWA Studio`} fill sizes="(max-width: 640px) 100vw, 33vw" className="object-cover transition-transform duration-700 ease-[var(--ease-out)] group-hover:scale-105" /></div><h2 className="mt-4 font-display text-xl font-bold uppercase">{project.title}</h2></Link>)}</div></section></div><section className="case-study-cta bg-red px-6 py-24 text-paper md:px-10 md:py-36"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[0.3em] text-paper/80">Ready to make it clearer?</p><h2 className="case-study-cta-title mt-6">Let&rsquo;s build your<br />online presence.</h2><Link href="/#contact" className="btn-press mt-12 inline-flex bg-ink px-7 py-4 text-xs font-bold uppercase tracking-[0.15em] text-paper transition-transform duration-200 hover:scale-105">Start a project →</Link></div></section></main><Footer /></>;
}
